# Generated by Django 4.2.1 on 2023-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '게시글들'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '댓글들'},
        ),
    ]
