# Generated by Django 4.2.1 on 2023-05-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_photos_photo_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photos',
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': '사진들'},
        ),
    ]
